POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "John Doe",
    "number": "123-123-1233"
}
###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Jane Doe",
    "number": "000-111-2222"
}
###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "",
    "number": "000-111-2222"
}
###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Name",
    "number": ""
}
###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "jane doe",
    "number": "000-111-2222"
}
###
POST https://fdagher-phonebook.fly.dev/api/persons
content-type: application/json

{
    "name": "John Doe",
    "number": "001-111-2222"
}